version: 3

vars:
  MONGODB_SHELL_VERSION:
    sh: curl https://api.github.com/repos/mongodb-js/mongosh/releases/latest | jq '.name'
  MONGODB_TOOLS_VERSION: 100.9.3  # Manually updated
  IMAGE_NAME: bushwhackr/mongodb-utils

tasks:
  run:
    desc: Run the mongodb-utils docker image
    cmds:
      - docker run -it --rm {{.IMAGE_NAME}}:latest

  build-local:
    desc: Build the mongodb-utils docker image
    cmds:
      - docker buildx build --build-arg MONGODB_SHELL_VERSION={{.MONGODB_SHELL_VERSION}} --build-arg MONGODB_TOOLS_VERSION={{.MONGODB_TOOLS_VERSION}} -t {{.IMAGE_NAME}}:latest .

  build:
    desc: Build the mongodb-utils docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 --build-arg MONGODB_SHELL_VERSION={{.MONGODB_SHELL_VERSION}} --build-arg MONGODB_TOOLS_VERSION={{.MONGODB_TOOLS_VERSION}} -t {{.IMAGE_NAME}}:latest -t {{.IMAGE_NAME}}:{{.MONGODB_TOOLS_VERSION }}_{{.MONGODB_SHELL_VERSION}} .

  publish:
    desc: Publish the mongodb-utils docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 --build-arg MONGODB_SHELL_VERSION={{.MONGODB_SHELL_VERSION}} --build-arg MONGODB_TOOLS_VERSION={{.MONGODB_TOOLS_VERSION}} -t {{.IMAGE_NAME}}:latest -t {{.IMAGE_NAME}}:{{.MONGODB_TOOLS_VERSION }}_{{.MONGODB_SHELL_VERSION}} . --push

  test:
    desc: Test the mongodb-utils docker image
    deps:
      - task: build-local
    cmds:
      - docker compose -f docker-compose.yaml up mongodb -d
      - defer: docker compose -f docker-compose.yaml down
      - docker compose -f docker-compose.yaml up mongodb-utils
      - docker compose -f docker-compose.yaml logs mongodb-utils | grep -Fq "done dumping"