name: "publish"

concurrency:
  cancel-in-progress: true
  group: mongodb-utils

permissions:
  id-token: write
  contents: read

on:
#  schedule:  # https://crontab.guru/#0_0_1_*_*
#    - cron: "0 0 1 * *"
  workflow_dispatch: {}

jobs:
  publish:
    name: Publish to dockerhub
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: task publish



